version: '3'
services:
  app:
    build: .
    container_name: kaggle_container
    volumes:
      - ./:/kaggle
    working_dir: /kaggle
    entrypoint: ["./run.sh"]
    ports:
      - 8888:8888
    tty: true